/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.google.protobuf.DescriptorProtos;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    @Test
    void protobufTest() {
        assertEquals(9, DescriptorProtos.Edition.values().length);
    }
}
